config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :index] do
    resource :father, only: [:show]
    resource :mother, only: [:show]
    resources :children, only: [:index]
  end
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :children, :class_name => "User"
  belongs_to :father, :class_name => "User", :foreign_key => 'father_id', optional: true
  belongs_to :mother, :class_name => "User", :foreign_key => 'mother_id', optional: true

  def children
    User.where('father_id=? or mother_id=?', id, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
  	@user = User.find(params[:user_id])
    @children = @user.children
  end
end

app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  def show
  	@user = User.find(params[:user_id])
    @father = @user.father
  end
end

app/controllers/mothers_controller.rb
class MothersController < ApplicationController
  def show
  	@user = User.find(params[:user_id])
    @mother = @user.mother
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/children/index.html.erb
<% @children.each do |child| %>
  <p>child name: <%= child.name %></p>
<% end %>
<p><%= link_to 'Back', users_path, class: "btn btn-primary" %></p>

app/views/fathers/show.html.erb
<div class="col-md-12">
  <p>Father Name: <%= @father.name %></p>
  <p><%= link_to 'Back', users_path, class: "btn btn-primary" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hindustani</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mothers/show.html.erb
<div class="col-md-12">
  <p>Mother Name: <%= @mother.name %></p>
  <p><%= link_to 'Back', users_path, class: "btn btn-primary" %></p>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <h1>Users list</h1>
  <br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Aadhar</th>
        <th>Birth date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th><%= user.name %></th>
          <th><%= user.aadhar %></th>
          <th><%= user.bdate %></th>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="text-center"><%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>  </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
  <p>Name: <%= @user.name %></p>
  <p>Aadhar: <%= @user.aadhar %></p>
  <p>Birth Date: <%= @user.bdate %></p>
  <% if @user.father_id %>
    <p><%= link_to 'Father', user_father_path(@user), class: "btn btn-sm btn-primary" %></p>
  <% end %>
  <% if @user.mother_id %>
    <p><%= link_to 'mother', user_mother_path(@user), class: "btn btn-sm btn-primary" %></p>
  <% end %>  
  <% if @user.children.present? %>
    <p><%= link_to 'children', user_children_path(@user), class: "btn btn-sm btn-primary" %></p>
  <% end %>
  <p><%= link_to 'Back', users_path, class: "btn btn-primary" %></p>	
</div>